name: Quickpick Dispatcher

on:
  push:
    branches:
      - main
  release:
    types: [published, edited, prereleased]
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: Bearsampp/bearsampp
          event-type: module_release_created
          client-payload: '{"module": "${{ github.repository }}"}'
